# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions

from ...commons.types.problem_id import ProblemId
from ...commons.types.test_case import TestCase
from .test_submission_status import TestSubmissionStatus


class TestSubmissionState(pydantic.BaseModel):
    problem_id: ProblemId = pydantic.Field(alias="problemId")
    default_test_cases: typing.List[TestCase] = pydantic.Field(alias="defaultTestCases")
    custom_test_cases: typing.List[TestCase] = pydantic.Field(alias="customTestCases")
    status: TestSubmissionStatus

    class Partial(typing_extensions.TypedDict):
        problem_id: typing_extensions.NotRequired[ProblemId]
        default_test_cases: typing_extensions.NotRequired[typing.List[TestCase]]
        custom_test_cases: typing_extensions.NotRequired[typing.List[TestCase]]
        status: typing_extensions.NotRequired[TestSubmissionStatus]

    class Validators:
        """
        Use this class to add validators to the Pydantic model.

            @TestSubmissionState.Validators.root
            def validate(values: TestSubmissionState.Partial) -> TestSubmissionState.Partial:
                ...

            @TestSubmissionState.Validators.field("problem_id")
            def validate_problem_id(problem_id: ProblemId, values: TestSubmissionState.Partial) -> ProblemId:
                ...

            @TestSubmissionState.Validators.field("default_test_cases")
            def validate_default_test_cases(default_test_cases: typing.List[TestCase], values: TestSubmissionState.Partial) -> typing.List[TestCase]:
                ...

            @TestSubmissionState.Validators.field("custom_test_cases")
            def validate_custom_test_cases(custom_test_cases: typing.List[TestCase], values: TestSubmissionState.Partial) -> typing.List[TestCase]:
                ...

            @TestSubmissionState.Validators.field("status")
            def validate_status(status: TestSubmissionStatus, values: TestSubmissionState.Partial) -> TestSubmissionStatus:
                ...
        """

        _validators: typing.ClassVar[
            typing.List[typing.Callable[[TestSubmissionState.Partial], TestSubmissionState.Partial]]
        ] = []
        _problem_id_validators: typing.ClassVar[typing.List[TestSubmissionState.Validators.ProblemIdValidator]] = []
        _default_test_cases_validators: typing.ClassVar[
            typing.List[TestSubmissionState.Validators.DefaultTestCasesValidator]
        ] = []
        _custom_test_cases_validators: typing.ClassVar[
            typing.List[TestSubmissionState.Validators.CustomTestCasesValidator]
        ] = []
        _status_validators: typing.ClassVar[typing.List[TestSubmissionState.Validators.StatusValidator]] = []

        @classmethod
        def root(
            cls, validator: typing.Callable[[TestSubmissionState.Partial], TestSubmissionState.Partial]
        ) -> typing.Callable[[TestSubmissionState.Partial], TestSubmissionState.Partial]:
            cls._validators.append(validator)
            return validator

        @typing.overload
        @classmethod
        def field(
            cls, field_name: typing_extensions.Literal["problem_id"]
        ) -> typing.Callable[
            [TestSubmissionState.Validators.ProblemIdValidator], TestSubmissionState.Validators.ProblemIdValidator
        ]:
            ...

        @typing.overload
        @classmethod
        def field(
            cls, field_name: typing_extensions.Literal["default_test_cases"]
        ) -> typing.Callable[
            [TestSubmissionState.Validators.DefaultTestCasesValidator],
            TestSubmissionState.Validators.DefaultTestCasesValidator,
        ]:
            ...

        @typing.overload
        @classmethod
        def field(
            cls, field_name: typing_extensions.Literal["custom_test_cases"]
        ) -> typing.Callable[
            [TestSubmissionState.Validators.CustomTestCasesValidator],
            TestSubmissionState.Validators.CustomTestCasesValidator,
        ]:
            ...

        @typing.overload
        @classmethod
        def field(
            cls, field_name: typing_extensions.Literal["status"]
        ) -> typing.Callable[
            [TestSubmissionState.Validators.StatusValidator], TestSubmissionState.Validators.StatusValidator
        ]:
            ...

        @classmethod
        def field(cls, field_name: str) -> typing.Any:
            def decorator(validator: typing.Any) -> typing.Any:
                if field_name == "problem_id":
                    cls._problem_id_validators.append(validator)
                if field_name == "default_test_cases":
                    cls._default_test_cases_validators.append(validator)
                if field_name == "custom_test_cases":
                    cls._custom_test_cases_validators.append(validator)
                if field_name == "status":
                    cls._status_validators.append(validator)
                return validator

            return decorator

        class ProblemIdValidator(typing_extensions.Protocol):
            def __call__(self, *, problem_id: ProblemId, values: TestSubmissionState.Partial) -> ProblemId:
                ...

        class DefaultTestCasesValidator(typing_extensions.Protocol):
            def __call__(
                self, *, default_test_cases: typing.List[TestCase], values: TestSubmissionState.Partial
            ) -> typing.List[TestCase]:
                ...

        class CustomTestCasesValidator(typing_extensions.Protocol):
            def __call__(
                self, *, custom_test_cases: typing.List[TestCase], values: TestSubmissionState.Partial
            ) -> typing.List[TestCase]:
                ...

        class StatusValidator(typing_extensions.Protocol):
            def __call__(
                self, *, status: TestSubmissionStatus, values: TestSubmissionState.Partial
            ) -> TestSubmissionStatus:
                ...

    @pydantic.root_validator
    def _validate(cls, values: TestSubmissionState.Partial) -> TestSubmissionState.Partial:
        for validator in TestSubmissionState.Validators._validators:
            values = validator(values)
        return values

    @pydantic.validator("problem_id")
    def _validate_problem_id(cls, problem_id: ProblemId, values: TestSubmissionState.Partial) -> ProblemId:
        for validator in TestSubmissionState.Validators._problem_id_validators:
            problem_id = validator(problem_id, values=values)
        return problem_id

    @pydantic.validator("default_test_cases")
    def _validate_default_test_cases(
        cls, default_test_cases: typing.List[TestCase], values: TestSubmissionState.Partial
    ) -> typing.List[TestCase]:
        for validator in TestSubmissionState.Validators._default_test_cases_validators:
            default_test_cases = validator(default_test_cases, values=values)
        return default_test_cases

    @pydantic.validator("custom_test_cases")
    def _validate_custom_test_cases(
        cls, custom_test_cases: typing.List[TestCase], values: TestSubmissionState.Partial
    ) -> typing.List[TestCase]:
        for validator in TestSubmissionState.Validators._custom_test_cases_validators:
            custom_test_cases = validator(custom_test_cases, values=values)
        return custom_test_cases

    @pydantic.validator("status")
    def _validate_status(
        cls, status: TestSubmissionStatus, values: TestSubmissionState.Partial
    ) -> TestSubmissionStatus:
        for validator in TestSubmissionState.Validators._status_validators:
            status = validator(status, values=values)
        return status

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        allow_population_by_field_name = True
