# This file was auto-generated by Fern from our API Definition.

import typing
import urllib

import pydantic
import requests

from ..types.migration import Migration


class Client:
    def __init__(self, *, environment: str):
        self._environment = environment

    def get_attempted_migrations(self) -> typing.List[Migration]:
        _response = requests.request("GET", urllib.parse.urljoin(f"{self._environment}/", "migration-info/all"))
        return pydantic.parse_obj_as(typing.List[Migration], _response)  # type: ignore
