# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import requests

from ...commons.types.language import Language
from ..types.execution_session_response import ExecutionSessionResponse
from ..types.get_execution_session_state_response import GetExecutionSessionStateResponse


class Client:
    def __init__(self, *, environment: str):
        ...

    def create_execution_session(self, *, language: Language) -> ExecutionSessionResponse:
        _response = requests.request("POST", "")
        return pydantic.parse_obj_as(ExecutionSessionResponse, _response)  # type: ignore

    def get_execution_session(self, *, session_id: str) -> typing.Optional[ExecutionSessionResponse]:
        _response = requests.request("GET", "")
        return pydantic.parse_obj_as(typing.Optional[ExecutionSessionResponse], _response)  # type: ignore

    def stop_execution_session(self, *, session_id: str) -> None:
        _response = requests.request("DELETE", "")

    def get_execution_sessions_state(self) -> GetExecutionSessionStateResponse:
        _response = requests.request("GET", "")
        return pydantic.parse_obj_as(GetExecutionSessionStateResponse, _response)  # type: ignore
