# This file was auto-generated by Fern from our API Definition.

import requests


class Client:
    def __init__(self, *, environment: str):
        ...

    def test(self) -> None:
        _response = requests.request("GET", "")
