# This file was auto-generated by Fern from our API Definition.

import typing_extensions

from ....core.api_error import ApiError
from ..types.playlist_id_not_found_error_body import PlaylistIdNotFoundErrorBody


class PlaylistIdNotFoundError(ApiError):
    def __init__(self, status_code: typing_extensions.Literal[404], body: PlaylistIdNotFoundErrorBody):
        super().__init__(status_code, body)
        self.status_code = status_code
        self.body = body
