# This file was auto-generated by Fern from our API Definition.

import typing
import urllib

import requests


class Client:
    def __init__(self, *, environment: str, x_random_header: typing.Optional[str]):
        self._environment = environment
        self.x_random_header = x_random_header

    def test(self) -> None:
        _response = requests.request(
            "GET", urllib.parse.urljoin(f"{self._environment}/", ""), headers={"X-Random-Header": self.x_random_header}
        )
