# This file was auto-generated by Fern from our API Definition.

import typing_extensions

from ....core.api_error import ApiError


class UnauthorizedError(ApiError):
    def __init__(self, status_code: typing_extensions.Literal[]):
        super().__init__(status_code)
        self.status_code = status_code
