# This file was auto-generated by Fern from our API Definition.

import typing
import urllib

import httpx
import pydantic

from ....core.remove_none_from_headers import remove_none_from_headers
from ..types.playlist import Playlist
from ..types.playlist_create_request import PlaylistCreateRequest
from ..types.playlist_id import PlaylistId
from ..types.update_playlist_request import UpdatePlaylistRequest


class Client:
    def __init__(self, *, environment: str, x_random_header: typing.Optional[str], token: typing.Optional[str]):
        self._environment = environment
        self.x_random_header = x_random_header
        self._token = token

    def create_playlist(self, *, service_param: int, request: PlaylistCreateRequest) -> Playlist:
        _response = httpx.request(
            "POST",
            urllib.parse.urljoin(f"{self._environment}/", f"v2/playlist/{service_param}/create"),
            json=request,
            headers=remove_none_from_headers(
                {
                    "X-Random-Header": self.x_random_header,
                    "Authorization": f"Bearer {self._token}" if self._token is not None else None,
                }
            ),
        )
        return pydantic.parse_obj_as(Playlist, _response)  # type: ignore

    def get_playlists(
        self,
        *,
        service_param: int,
        limit: typing.Optional[int],
        other_field: str,
        multi_line_docs: str,
        optional_multiple_field: typing.Optional[str],
        multiple_field: str,
    ) -> typing.List[Playlist]:
        _response = httpx.request(
            "GET",
            urllib.parse.urljoin(f"{self._environment}/", f"v2/playlist/{service_param}/all"),
            params={
                "limit": limit,
                "otherField": other_field,
                "multiLineDocs": multi_line_docs,
                "optionalMultipleField": optional_multiple_field,
                "multipleField": multiple_field,
            },
            headers=remove_none_from_headers(
                {
                    "X-Random-Header": self.x_random_header,
                    "Authorization": f"Bearer {self._token}" if self._token is not None else None,
                }
            ),
        )
        return pydantic.parse_obj_as(typing.List[Playlist], _response)  # type: ignore

    def get_playlist(self, *, service_param: int, playlist_id: PlaylistId) -> Playlist:
        _response = httpx.request(
            "GET",
            urllib.parse.urljoin(f"{self._environment}/", f"v2/playlist/{service_param}/{playlist_id}"),
            headers=remove_none_from_headers(
                {
                    "X-Random-Header": self.x_random_header,
                    "Authorization": f"Bearer {self._token}" if self._token is not None else None,
                }
            ),
        )
        return pydantic.parse_obj_as(Playlist, _response)  # type: ignore

    def update_playlist(
        self, *, service_param: int, playlist_id: PlaylistId, request: typing.Optional[UpdatePlaylistRequest]
    ) -> typing.Optional[Playlist]:
        _response = httpx.request(
            "PUT",
            urllib.parse.urljoin(f"{self._environment}/", f"v2/playlist/{service_param}/{playlist_id}"),
            json=request,
            headers=remove_none_from_headers(
                {
                    "X-Random-Header": self.x_random_header,
                    "Authorization": f"Bearer {self._token}" if self._token is not None else None,
                }
            ),
        )
        return pydantic.parse_obj_as(typing.Optional[Playlist], _response)  # type: ignore

    def delete_playlist(self, *, service_param: int, playlist_id: PlaylistId) -> None:
        _response = httpx.request(
            "DELETE",
            urllib.parse.urljoin(f"{self._environment}/", f"v2/playlist/{service_param}/{playlist_id}"),
            headers=remove_none_from_headers(
                {
                    "X-Random-Header": self.x_random_header,
                    "Authorization": f"Bearer {self._token}" if self._token is not None else None,
                }
            ),
        )
