# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import requests

from ...commons.types.language import Language


class Client:
    def __init__(self, *, environment: str):
        ...

    def set_num_warm_instances(self, *, language: Language, num_warm_instances: int) -> None:
        _response = requests.request("PUT", "")

    def get_num_warm_instances(self) -> typing.Dict[Language, int]:
        _response = requests.request("GET", "")
        return pydantic.parse_obj_as(typing.Dict[Language, int], _response)  # type: ignore
