# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import requests

from ...commons.types.problem_id import ProblemId


class Client:
    def __init__(self, *, environment: str):
        ...

    def get_homepage_problems(self) -> typing.List[ProblemId]:
        _response = requests.request("GET", "")
        return pydantic.parse_obj_as(typing.List[ProblemId], _response)  # type: ignore

    def set_homepage_problems(self, *, request: typing.List[ProblemId]) -> None:
        _response = requests.request("POST", "", json=request)
