# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import requests

from ..types.migration import Migration


class Client:
    def __init__(self, *, environment: str):
        ...

    def get_attempted_migrations(self) -> typing.List[Migration]:
        _response = requests.request("GET", "")
        return pydantic.parse_obj_as(typing.List[Migration], _response)  # type: ignore
