version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  check:
    docker:
      - image: cimg/python:3.8.16-node
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Type check
          command: poetry run mypy
      - run:
          name: pre-commit
          command: poetry run pre-commit run --all-files

  test:
    docker:
      - image: cimg/python:3.8.16-node
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest -sv

  publish-dockers:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Setup Buildx
          command: |
            docker buildx create --name multiplatform --driver docker-container --bootstrap --use
      - run:
          name: Publish Pydantic Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/pydantic-model/Dockerfile -t fernapi/fern-pydantic-model:${projectVersion} . --push
      - run:
          name: Publish FastAPI Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/fastapi/Dockerfile -t fernapi/fern-fastapi-server:${projectVersion} . --push
      - run:
          name: Publish SDK Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/sdk/Dockerfile -t fernapi/fern-python-sdk:${projectVersion} . --push

workflows:
  build:
    jobs:
      - check:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - publish-dockers:
          filters:
            branches:
              only: main
            tags:
              only:
                - /.*/
          requires:
            - check
            - test
          context:
            - docker-hub
